# Generated by Django 3.1.2 on 2020-11-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_card_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
