# Generated by Django 3.1.2 on 2020-11-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
    ]
