# Generated by Django 3.1.2 on 2020-11-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='hide_completed',
            field=models.BooleanField(default=False),
        ),
    ]
